name: check for caddy and plugin updates

on:
  # Possibility to run it manually
  workflow_dispatch:
    inputs:
      trigger_all_builds:
        description: build all images
        default: false
        type: boolean
        required: true
  push:
    paths:
      - ".github/workflows/main-workflow.yml"
      - ".github/workflows/build-image.yml"
      - ".github/workflows/update-commit.yml"
      - "Dockerfile-desec"
      - "Dockerfile-desec-alpine"
      - "commit-check.sh"
  # Automated
  schedule:
    # Run Every hour
    - cron: "0 * * * *"

jobs:
  check-for-new-caddy-release:
    runs-on: ubuntu-latest
    outputs:
      caddy: ${{ steps.git-check.outputs.caddy-out-of-date }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/caddyserver/caddy/releases/latest | \
          jq -r ".tag_name" > git-hashes/caddy-release.txt

      - name: Check for modified files
        id: git-check
        run: echo "caddy-out-of-date=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT

  update-caddy-build-version:
    runs-on: ubuntu-latest
    needs: check-for-new-caddy-release
    if: ${{ needs.check-for-new-caddy-release.outputs.caddy == 'true' }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/caddyserver/caddy/releases/latest | \
          jq -r ".tag_name" > git-hashes/caddy-release.txt

      - name: Commit latest build version
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add git-hashes/caddy-release.txt
          git commit -am "update current caddy build version"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  check-for-plugin-updates:
    runs-on: ubuntu-latest
    needs: check-for-new-caddy-release
    outputs:
      desec: ${{ steps.desec.outputs.desec-out-of-date || steps.caddy-check.outputs.desec-out-of-date }}
      cloudflare: ${{ steps.cloudflare.outputs.cloudflare-out-of-date || steps.caddy-check.outputs.cloudflare-out-of-date }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: trigger all builds if there is a new caddy release or if requested
        if: ${{ github.event.inputs.trigger_all_builds == 'true' || needs.check-for-new-caddy-release.outputs.caddy == 'true' }}
        id: caddy-check
        run: |
          echo "desec-out-of-date=true" >> $GITHUB_OUTPUT
          echo "cloudflare-out-of-date=true" >> $GITHUB_OUTPUT

      - name: Pull desec plugin remote commits
        if: ${{ github.event.inputs.trigger_all_builds == 'false' || github.event.inputs.trigger_all_builds == '' && needs.check-for-new-caddy-release.outputs.caddy == 'false' }} #workaround, github inputs will be empty by default
        id: desec
        run: sh commit-check.sh https://github.com/caddy-dns/desec desec-local.txt git-hashes/desec.txt desec-out-of-date

      - name: Pull cloudflare plugin remote commits
        if: ${{ github.event.inputs.trigger_all_builds == 'false' || github.event.inputs.trigger_all_builds == '' && needs.check-for-new-caddy-release.outputs.caddy == 'false' }} #workaround, github inputs will be empty by default        
        id: cloudflare
        run: sh commit-check.sh https://github.com/caddy-dns/cloudflare cloudflare-local.txt git-hashes/cloudflare.txt cloudflare-out-of-date

  trigger-desec-build:
    needs: check-for-plugin-updates
    if: ${{ needs.check-for-plugin-updates.outputs.desec == 'true' }}
    uses: FarisZR/caddy-dns-OCI/.github/workflows/start-build.yml@main
    permissions:
      packages: write
      contents: write
    with:
      dockerfile: Dockerfile
      dockerfile_alpine: Dockerfile-alpine
      image_title: Caddy with desec dns plugin
      license: MIT
      tag: desec
      alpine_tag: desec-alpine
      go_plugin_link: github.com/caddy-dns/desec
      hash_file: git-hashes/desec.txt
      plugin_name: desec
      repo: https://github.com/caddy-dns/desec

  trigger-cloudflare-build:
    needs: check-for-plugin-updates
    if: ${{ needs.check-for-plugin-updates.outputs.cloudflare == 'true' }}
    uses: FarisZR/caddy-dns-OCI/.github/workflows/start-build.yml@main
    permissions:
      packages: write
      contents: write
    with:
      dockerfile: Dockerfile
      dockerfile_alpine: Dockerfile-alpine
      image_title: Caddy with cloudflare dns plugin
      license: MIT
      tag: cloudflare
      alpine_tag: cloudflare-alpine
      go_plugin_link: github.com/caddy-dns/cloudflare
      hash_file: git-hashes/cloudflare.txt
      plugin_name: cloudflare
      repo: https://github.com/caddy-dns/cloudflare